#!/usr/bin/env bash

brew_install 'node'
brew_install 'rbenv'
brew_install 'git'
brew_install 'neovim/neovim/neovim'
brew_install 'tmux'
brew_install 'reattach-to-user-namespace'
brew_install 'python'
brew_install 'python3'
brew_install 'shellcheck'
brew_install 'coreutils'
brew_install 'ansible'

brew_install 'wget'
brew_install 'tig'
brew_install 'fzf'
brew_install 'openssl'
brew_install 'hub'
brew_install 'httpie'
brew_install 'jq'
brew_install 'diff-so-fancy'
brew_install 'the_silver_searcher'

brew_install 'asciinema'
brew_install 'm-cli'
brew_install 'htop'
brew_install 'figlet'
brew_install 'tree'
